package main.service;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import main.ReaderDAO;
import main.domain.Reader;

public class ReaderManager implements ReaderDAO
{

    private Connection connection;

    private String url = "jdbc:sqlserver://eos.inf.ug.edu.pl;" + "databaseName=mzweigert" + ";user=mzweigert" + ";password=224667";

    private String createTableReader = "CREATE TABLE Reader(idReader bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(20), surname varchar(20), join_date Date, extra_points int)";

    private PreparedStatement getAllReadersStmt;
    private PreparedStatement getReaderByIdStmt;
    private PreparedStatement getReaderBySurnameStmt;
    private PreparedStatement updateReaderStmt;
    private PreparedStatement deleteReaderStmt;

    private PreparedStatement addReaderStmt;
    private PreparedStatement deleteAllReadersStmt;


    private Statement statement;

    public ReaderManager()
    {
        try
        {
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
            boolean tableExists = false;
            while (rs.next())
            {
                if ("Reader".equalsIgnoreCase(rs.getString("TABLE_NAME")))
                {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTableReader);

            getAllReadersStmt = connection.prepareStatement("SELECT idReader, name, surname, join_date, extra_points FROM Reader");
            getReaderByIdStmt = connection.prepareStatement("SELECT * FROM Reader WHERE idReader = ?");
            getReaderBySurnameStmt = connection.prepareStatement("SELECT * FROM Reader WHERE surname='?' ");
            updateReaderStmt = connection.prepareStatement("UPDATE Reader SET name='?', surname='?', join_date = '?', extra_points = ? WHERE idReader = ?");
            deleteReaderStmt = connection.prepareStatement("DELETE Reader WHERE idReader = ?");
            addReaderStmt = connection.prepareStatement("INSERT INTO Reader (name, surname, join_date, extra_points) VALUES (?, ?, ?, ?)");
            deleteAllReadersStmt = connection.prepareStatement("DELETE FROM Reader");


        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }

    }

    Connection getConnection()
    {
        return connection;
    }
    public List<Reader> getAllReaders()
    {
        List<Reader> readers = new ArrayList<Reader>();
        Reader reader;
        try
        {
            ResultSet rs = getAllReadersStmt.executeQuery();

            while (rs.next())
            {
                reader = new Reader( rs.getString("name"), rs.getString("surname"), rs.getDate("join_date"), rs.getInt("extra_points"));
                reader.setIdReader(rs.getInt("idReader"));
                readers.add(reader);
            }

        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return readers;
    }

    @Override
    public Reader getReaderById(int idReader)
    {
        Reader reader;
        try
        {
            getReaderByIdStmt.setInt(1, idReader);
            ResultSet rs = getReaderByIdStmt.executeQuery();

            while (rs.next())
            {
                reader = new Reader(rs.getString("name"), rs.getString("surname"), rs.getDate("join_date"),rs.getInt("extra_points"));
                reader.setIdReader(rs.getInt("idReader"));
                return reader;
            }
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }

        return null;
    }

    @Override
    public List<Reader> getReadersBySurname(String surname)
    {
        List<Reader> readersBySurname = new ArrayList<Reader>();
        Reader reader;
        try
        {
            getReaderBySurnameStmt.setString(1, surname);
            ResultSet rs = getReaderBySurnameStmt.executeQuery();

            while (rs.next())
            {
                reader = new Reader(rs.getString("name"), rs.getString("surname"), rs.getDate("join_date"),rs.getInt("extra_points"));
                reader.setIdReader(rs.getInt("idReader"));
                readersBySurname.add(reader);
            }

            return readersBySurname;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }

        return null;
    }

    @Override
    public boolean updateReader(Reader reader)
    {
        try
        {
            updateReaderStmt.setString(1, reader.getName());
            updateReaderStmt.setString(2, reader.getSurname());
            updateReaderStmt.setDate(3, reader.getJoinDate());
            updateReaderStmt.setInt(4, reader.getExtraPoints());
            updateReaderStmt.setInt(5, reader.getIdReader());

            updateReaderStmt.executeUpdate();
            return true;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return false;
    }

    @Override
    public boolean deleteReader(Reader reader)
    {
        try
        {
            deleteReaderStmt.setInt(1, reader.getIdReader());
            deleteReaderStmt.executeUpdate();
            return true;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }

        return false;
    }

    public boolean addReader(Reader Reader)
    {

        try
        {
            addReaderStmt.setString(1, Reader.getName());
            addReaderStmt.setString(2, Reader.getSurname());
            addReaderStmt.setDate(3, Reader.getJoinDate());
            addReaderStmt.setInt(4, Reader.getExtraPoints());

            addReaderStmt.executeUpdate();
            return  true;
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
        return false;
    }

    void clearReaders()
    {
        try
        {
            deleteAllReadersStmt.executeUpdate();
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
    }


}